#!/bin/bash

# This script submits a job with sbatch with the ressources specified in the config.sh file. 
# To run this script cd into the repo's directory and use : bash tractometry/run_tractometry_cc.sh your_config.sh
# ex :  bash tractometry/run_tractometry_cc.sh config_test.sh

# Define the path to the configuration file
DEFAULT_CONFIG_FILE="config_ex.sh"

# Check if an argument is provided
if [ "$#" -eq 1 ]; then
    CONFIG_FILE="$1"
else
    CONFIG_FILE="$DEFAULT_CONFIG_FILE"
fi

# Check if the config file exists
if [ -f "$CONFIG_FILE" ]; then
    # Source the config file
    source "$CONFIG_FILE"
    echo "Using config file: $CONFIG_FILE"
else
    echo "Error: Config file '$CONFIG_FILE' not found."
    exit 1
fi


my_singularity_img="${TOOLS_PATH}/containers/scilus_1.6.0.sif" # or .img
my_main_nf="${TOOLS_PATH}/tractometry_flow/main.nf"

if [ -n "${tractometry_inputs+x}" ]; then
    if [ -n "$tractometry_inputs" ]; then
        my_input=$tractometry_inputs
    else
        echo "The variable tractometry_inputs is empty in $CONFIG_FILE, check if combineflow_for_tractometry_cc.sh has finished sucsessfully"
        exit 1
    fi
else
    echo "No input folder for tractometry was found. Have you run combineflow_for_tractometry_cc.sh ? If you are tryning to run tractometry on a folder that wasn't generated by combineflow_for_tractometry_cc.sh and with the same config file, you need to set/add the tractometry_inputs variable manually in your config file"
    exit 1
fi

my_input=$tractometry_inputs
current_date=$(date +"%Y-%m-%d")

if [ ! -n "${nb_points}" ]; then
    nb_points='20' # 20 is the default nb of points that tractometry segments the tracks
fi

cmd="nextflow run $my_main_nf \
    --input $my_input \
    -with-singularity $my_singularity_img -resume \
    --skip_projection_endpoints_metrics \
    --use_provided_centroids false \
    --skip_projection_endpoints_metrics \
    --nb_points $nb_points"



TMP_SCRIPT=$(mktemp /tmp/slurm-tractometry_XXXXXX.sh)

# Write the SLURM script to the temporary file
cat <<EOT > $TMP_SCRIPT
#!/bin/bash
$tractometry_ressources

# Load necessary module
module load StdEnv/2020 java/14.0.2 nextflow/21.10.3 apptainer

# cd $my_input
cd /home/ludoal/scratch/tpil_data/tractometry_issue/tractometry_results

# Create a readme.txt to keep track of options and date that this was ran
echo -e "Tractometry pipeline\n" > readme.txt
echo -e "Date : $current_date\n" > readme.txt
echo -e "[Command-Line]\n" > readme.txt
echo "$cmd" > readme.txt


$cmd

EOT

# uncomment to print the script in the terminal
# cat $TMP_SCRIPT

# Submit the scipt as a slurm job
sbatch $TMP_SCRIPT

