#!/bin/bash

# This would run RecobundleX with the following parameters:
#   - Population average atlas for RecobundlesX. DOI:  10.5281/zenodo.10103446

# This script submits a job with sbatch with the ressources specified in the config.sh file. 
# To run this script use : bash bundleseg/run_rbx_cc.sh your_config.sh
#  


# Define the path to the configuration file
DEFAULT_CONFIG_FILE="config_ex.sh"

# Check if an argument is provided
if [ "$#" -eq 1 ]; then
    CONFIG_FILE="$1"
else
    CONFIG_FILE="$DEFAULT_CONFIG_FILE"
fi

# Check if the config file exists
if [ -f "$CONFIG_FILE" ]; then
    # Source the config file
    source "$CONFIG_FILE"
    echo "Using config file: $CONFIG_FILE"
else
    echo "Error: Config file '$CONFIG_FILE' not found."
    exit 1
fi


my_singularity_img="${TOOLS_PATH}/containers/scilus_1.6.0.sif" # or .img
my_main_nf="${TOOLS_PATH}/rbx_flow/main.nf"
my_atlas_dir="${TOOLS_PATH}/atlas_dir"

if [ -n "${rbx_inputs+x}" ]; then
    if [ -n "$rbx_inputs" ]; then
        my_input=$rbx_inputs
    else
        echo "The variable rbx_inputs is empty in $CONFIG_FILE, check if combineflow_for_rbx has finished sucsessfully"
        exit 1
    fi
else
    echo -e "No input folder for rbx was found. Have you run combineflow_for_rbx_cc.sh ? \nIf you are tryning to run rbx on a folder that wasn't generated by combineflow_for_rbx_cc.sh and with the same config file, you need to set/add the rbx_inputs variable manually in your config file"
    exit 1
fi



cmd="NXF_DEFAULT_DSL=1 nextflow run $my_main_nf \
    --input $my_input \
    -with-singularity $my_singularity_img \
    -with-report report.html \
    --atlas_directory $my_atlas_dir \
    -resume"



TMP_SCRIPT=$(mktemp /tmp/slurm-rbx_XXXXXX.sh)

# Write the SLURM script to the temporary file
cat <<EOT > $TMP_SCRIPT
#!/bin/bash
$rbx_ressources


# Load necessary module
module load StdEnv/2020 java/14.0.2 nextflow/21.10.3 apptainer

cd $my_input

# Create a readme.txt to keep track of options and date that this was ran
current_date=$(date)
echo -e "Rbx pipeline\n" > readme.txt
echo -e "Date : $current_date\n" > readme.txt
echo -e "[Command-Line]\n" > readme.txt
echo $cmd > readme.txt

$cmd


EOT

# uncomment to print the script in the terminal
# cat $TMP_SCRIPT

# Submit the scipt as a slurm job
sbatch $TMP_SCRIPT

